---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    # Can be any supported provider (virtualbox, parallels, libvirt, etc)
    # Defaults to virtualbox
    name: virtualbox
platforms:
  - name: instance
    box: generic/centos8
    memory: 2048
    cpus: 2
    interfaces:
      # `network_name` is the required identifier, all other keys map to
      # arguments.
      - auto_config: true
        network_name: private_network
        type: dhcp
      - network_name: private_network
        ip: 192.168.56.14
      - network_name: forwarded_port
        guest: 80
        host: 8080
provisioner:
  name: ansible
verifier:
  name: inspec
