---
# This is an example playbook to execute inspec tests.
# Tests need distributed to the appropriate ansible host/groups
# prior to execution by `inspec exec`.

- name: Verify
  hosts: all
  become: true
  vars:
    inspec_bin: /opt/inspec/bin/inspec
    inspec_download_source_dir: /usr/local/src
    inspec_test_directory: /tmp/molecule/inspec
    ansible_pkg_mgr: yum
  tasks:
    # - name: Setting variables (CentOS 8 / RHEL 7 / Amazon Linux 2)
    #   set_fact:
    #     inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.9.3/el/7/inspec-3.9.3-1.el7.x86_64.rpm"
    #     inspec_download_sha256sum: 4d54d12899c2eeaae4812cd13b8dfcae01ec1fd4a44f00cab77e31a57aea502b
    #   when: (ansible_facts['os_family'] == "RedHat" and (ansible_facts['distribution_major_version'] == "8" or ansible_facts['distribution_major_version'] == "2"))

    # - name: Download Inspec
    #   get_url:
    #     url: "{{ inspec_download_url }}"
    #     dest: "{{ inspec_download_source_dir }}"
    #     sha256sum: "{{ inspec_download_sha256sum }}"
    #     mode: 0755

    # - name: Install Inspec (apt)
    #   apt:
    #     deb: "{{ inspec_download_source_dir }}/{{ inspec_download_url.split('/')[-1] }}"
    #     state: present
    #   when: ansible_pkg_mgr == "apt"

    # - name: Install Inspec (yum)
    #   yum:
    #     name: "{{ inspec_download_source_dir }}/{{ inspec_download_url.split('/')[-1] }}"
    #     state: present
    #   become: true
    #   when: ansible_pkg_mgr == "yum"

    # - name: Install Inspec (yum)
    #   yum:
    #     name: inspec
    #     state: installed
    #   become: true
    #   when: ansible_pkg_mgr == "yum"

    - name: Create inspec test directory
      file:
        path: "{{ inspec_test_directory }}"
        state: directory

    - name: Copy inspec test directories
      file:
        path: "{{ inspec_test_directory }}/{{ item.path }}"
        state: directory
        mode: 0755
      with_filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'directory'

    - name: Copy inspec test files
      copy:
        src: "{{ item.src }}"
        dest: "{{ inspec_test_directory }}/{{ item.path }}"
        mode: 0644
      with_filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'file'

    - name: Execute Inspec tests
      command: "{{ inspec_bin }} exec {{ inspec_test_directory }}"
      register: test_results
      ignore_errors: true

    - name: Display details about the Inspec results
      debug:
        msg: "{{ test_results.stdout_lines | replace('u001b[38;5;41m', '') | replace('u001b[0m', '')}}"

    - name: Fail when tests fail
      fail:
        msg: "Inspec failed to validate"
      when: test_results.rc != 0
